TaskForLightpoint/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TaskForLightpoint.Data;
using TaskForLightpoint.Models;
using TaskForLightpoint.Services;

namespace TaskForLightpoint.Controllers
{
    public class ShopController : Controller
    {
        private readonly IShopService _shopService;

        public ShopController(IShopService shopService)
        {
            _shopService = shopService;
        }

        // GET: Shop
        public async Task<IActionResult> Index()
        {
            return View(_shopService.GetAllShops());
        }

        // GET: Shop/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = _shopService.GetShop(id.Value);
            if (shop == null)
            {
                return NotFound();
            }

            return View(shop);
        }

        // GET: Shop/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Shop/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Adress,OpeningHours")] Shop shop)
        {
            if (ModelState.IsValid)
            {
                shop.Id = Guid.NewGuid();
               _shopService.CreateShop(shop);
                return RedirectToAction(nameof(Index));
            }
            return View(shop);
        }

        // GET: Shop/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = _shopService.GetShop(id.Value);
            if (shop == null)
            {
                return NotFound();
            }
            return View(shop);
        }

        // POST: Shop/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Adress,OpeningHours")] Shop shop)
        {
            if (id != shop.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _shopService.UpdateShop(shop);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShopExists(shop.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shop);
        }

        // GET: Shop/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = _shopService.GetShop(id.Value);
            if (shop == null)
            {
                return NotFound();
            }

            return View(shop);
        }

        // POST: Shop/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            _shopService.DeleteShop(id);
            return RedirectToAction(nameof(Index));
        }

        private bool ShopExists(Guid id)
        {
            return _shopService.ShopExist(id);
        }
    }
}

TaskForLightpoint/Controllers/ShopProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TaskForLightpoint.Data;
using TaskForLightpoint.Models;
using TaskForLightpoint.Services;

namespace TaskForLightpoint.Controllers
{
    public class ShopProductController : Controller
    {

        private readonly IShopService _shopService;

        private readonly IProductService _productService;

        public ShopProductController(IShopService shopService, IProductService productService)
        {
            _shopService = shopService;
            _productService = productService;
        }

        // GET: ShopProduct
        public async Task<IActionResult> Index()
        {
            return View(_shopService.GetAllShopsProducts());
        }

        // GET: ShopProduct/Products/5
        public async Task<IActionResult> Products(Guid id)
        {
            ViewBag.Asd = id;
            return View("Index", _shopService.GetProductsByShopId(id));
        }

        /*// GET: ShopProduct/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shopProduct = _shopService.GetShopProduct(id.Value);
            if (shopProduct == null)
            {
                return NotFound();
            }

            return View(shopProduct);
        }*/

        // GET: ShopProduct/Create
        public IActionResult Create(Guid id)
        {
            ViewData["ProductFK"] = new SelectList(_productService.GetAllProducts().Result, "Id", "Name");
            ViewData["ShopFK"] = new SelectList(_shopService.GetAllShops(), "Id", "Name", id);
            ViewBag.ShopId = id;
            return View();
        }

        // POST: ShopProduct/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ShopFK,ProductFK")] ShopProduct shopProduct)
        {
            if (ModelState.IsValid)
            {
                shopProduct.Id = Guid.NewGuid();
                _shopService.CreateShopProduct(shopProduct);
                return RedirectToAction("Products", new { id = shopProduct.ShopFK });
            }
            ViewData["ProductFK"] = new SelectList(_productService.GetAllProducts().Result, "Id", "Name", shopProduct.ProductFK);
            ViewData["ShopFK"] = new SelectList(_shopService.GetAllShops(), "Id", "Name", shopProduct.ShopFK);
            return View(shopProduct);
            //return RedirectToAction(nameof(Index));
        }

        // GET: ShopProduct/Edit/5
        /*public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shopProduct = _shopService.GetShopProduct(id.Value);
            if (shopProduct == null)
            {
                return NotFound();
            }
            ViewData["ProductFK"] = new SelectList(_productService.GetAllProducts().Result, "Id", "Name", shopProduct.ProductFK);
            ViewData["ShopFK"] = new SelectList(_shopService.GetAllShops(), "Id", "Name", shopProduct.ShopFK);
            return View(shopProduct);
        }

        // POST: ShopProduct/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,ShopFK,ProductFK")] ShopProduct shopProduct)
        {
            if (id != shopProduct.ShopFK)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _shopService.UpdateShopProduct(shopProduct);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShopProductExists(shopProduct.ShopFK))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductFK"] = new SelectList(_productService.GetAllProducts().Result, "Id", "Name", shopProduct.ProductFK);
            ViewData["ShopFK"] = new SelectList(_shopService.GetAllShops(), "Id", "Name", shopProduct.ShopFK);
            return View(shopProduct);
        }*/

        // GET: ShopProduct/Delete/5
        /*public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shopProduct = _shopService.GetShopProduct(id.Value);
            if (shopProduct == null)
            {
                return NotFound();
            }

            return View(shopProduct);
        }

        // POST: ShopProduct/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            _shopService.DeleteShopProduct(id);
            return RedirectToAction(nameof(Index));
        }*/

        private bool ShopProductExists(Guid id)
        {
            return _shopService.ShopProductExist(id);
        }
    }
}

TaskForLightpoint/Views/ShopProduct/Create.cshtml
@model TaskForLightpoint.Models.ShopProduct

@{
    ViewData["Title"] = "Add a new product to the shop";
}

<h3>Add a new product to the selected shop</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ShopFK" class="control-label"></label>
                <input data-val="true" data-val-required="The Shop field is required." id="ShopFK" name="ShopFK" type="hidden" value="@ViewBag.ShopId">
                @* @Html.HiddenFor(model => model.ShopFK) *@
                <select name="shop" asp-for="ShopFK" disabled="true" class="form-control" asp-items="ViewBag.ShopFK"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductFK" class="control-label"></label>
                <select asp-for="ProductFK" class ="form-control" asp-items="ViewBag.ProductFK"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Shop" asp-action="Index">Back to all shops</a>
    @*<a asp-controller="ShopProduct" asp-action="Products" asp-route-id="@item.Id">Show all products</a> |*@
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskForLightpoint/Views/ShopProduct/Delete.cshtml
@model TaskForLightpoint.Models.ShopProduct

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ShopProduct</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Shop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Shop.Adress)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.Description)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ShopFK" />
        <input type="hidden" asp-for="ProductFK" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TaskForLightpoint/Views/ShopProduct/Details.cshtml
@model TaskForLightpoint.Models.ShopProduct

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ShopProduct</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Shop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Shop.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

TaskForLightpoint/Views/ShopProduct/Edit.cshtml
@model TaskForLightpoint.Models.ShopProduct

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ShopProduct</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="ShopFK" />
            <input type="hidden" asp-for="ProductFK" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskForLightpoint/Views/ShopProduct/Index.cshtml
@model IEnumerable<TaskForLightpoint.Models.ShopProduct>

@{
    ViewData["Title"] = "All products in a shop";
}

<h3>All products in this shop</h3>

<p>
    <a asp-action="Create" asp-route-id="@ViewBag.Asd">Add a new product to this shop</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Shop)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Shop.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product.Name)
            </td>
            @*<td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>*@
        </tr>
}
    </tbody>
</table>